cocktail23/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('recipes.urls'), name='recipes-urls'),
    path('accounts/', include('allauth.urls')),
]

recipes/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.RecipeList.as_view(), name='home'),
    path('<slug:slug>/', views.RecipeDetail.as_view(), name='recipe'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))

class Recipe(models.Model):
    """
    Recipe Model
    """
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="cocktail")
    featured_image = CloudinaryField('image', default='placeholder')
    featured_image_alt = models.CharField(max_length=100, null=False, blank=False, default='green-lime-cocktail')
    serving = models.IntegerField()
    time = models.IntegerField()
    description = models.TextField(blank=False)
    updated_on = models.DateTimeField(auto_now=True)
    ingredients = models.TextField(blank=False)
    directions = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(User, related_name='cocktail_like', blank=True)

    class Meta:
        """
        Displays newest created-on cocktails
        """
        ordering = ["-created_on"]

    def __str__(self):
        return self.name

    def number_of_likes(self):
        """
        Displays total number of likes
        """
        return self.likes.count()


class Comment(models.Model):
    """
    Comment Model
    """
    cocktail = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        """
        Displays user comments from oldest to newest
        """
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"        

recipes/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic, View
from .models import Recipe


class RecipeList(generic.ListView):
    """
    Displays header and most recent added cocktails
    """
    model = Recipe
    queryset = Recipe.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'
    paginate_by = 6


class RecipeDetail(View):
    """
    Displays cocktail recipe details for logged-in users
    Logged users can like and leave a comment
    """
    def get(self, request, slug, *args, **kwargs):
        queryset = Recipe.objects.filter(status=1)
        cocktail = get_object_or_404(queryset, slug=slug)
        comments = cocktail.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if cocktail.likes.filter(id=self.request.user.id).exists():
            liked = True 

        return render(
            request,
            "recipe.html",
            {
                "cocktail": cocktail,
                "commented": False, 
                "liked": liked,
            },
        )       

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <title>Cocktail Heaven</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}"><span class="brand"><img src="{% static 'images/logo.jpg' %}" width="80" alt="cocktail"><span
                        class="thin">|heaven</span></span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarText">
                <ul class="navbar-nav ml-auto mb-2  mb-lg-2">
                    <li class="nav-item fs-6">
                        <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home |</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item fs-6">
                        <a class="nav-link" href="#">Add Cocktail |</a>
                    </li>  
                    <li class="nav-item fs-6">
                        <a class="nav-link" href="#">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item fs-6">
                        <a class="nav-link" href="#">Register |</a>
                    </li>
                    <li class="nav-item fs-6">
                        <a class="nav-link" href="#">Login</a>
                    </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>
    
    <!-- Block content -->
    <main class="flex-shrink-0 main-bg">
        {% block content %}
        
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mx-auto py-3 bg-white d-inline-flex">       
        <p class="m-0 text-center text-muted">&copy; 2023|</p>
        <p class="m-0 text-center text-muted">Follow Us:
            <a href="https://facebook.com" target="_blank" aria-label="Follow on Facebook" class="text-muted"><i class="fab fa-facebook-square ms-1"></i></a>
            <a href="https://twitter.com" target="_blank" aria-label="Follow on Twiter" class="text-muted"><i class="fab fa-twitter-square ms-3"></i></a>
            <a href="https://instagram.com" target="_blank" aria-label="Follow on Instagram" class="text-muted"><i class="fab fa-instagram-square ms-3"></i></a>
        </p>     
    </footer>

</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <!-- Cocktail column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for recipe in recipe_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in recipe.featured_image.url %}
                                <img class="card-img-top img-thumbnail" style="width: 100%; height: 100%;"
                                    src="https://res.cloudinary.com/dinbzvx8s/image/upload/v1699958086/static/images/cocktail.7062657aa641.jpg" width="100%" alt="mohito-cocktail-glass">
                                {% else %}
                                <img class="card-img-top img-thumbnail" src=" {{ recipe.featured_image.url }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="cocktail h6"><strong>Cocktail - {{ recipe.name }}</strong></p>
                                </div>
                                <div class="post-link">
                                    <p class="card-text">{{ recipe.description }}</p>
                                    {% if user.is_authenticated %}
                                    <div class="recipe-link">
                                        <a href="{% url 'recipe' recipe.slug %}"><i class="fa fa-arrow-right"></i> Get
                                            The
                                            {{ recipe.name }} Recipe</a>
                                    </div>
                                    {% else %}
                                    <p class="d-grid gap-2 col-12 mx-auto bold"><section>To view {{ recipe.name }} recipe <a
                                        class="link" href="#">Login</a> or <a
                                        class="link" href="#">Register</a> an account!</section></p>
                                    {% endif %}
                            
                                </div>

                            </div>
                            <hr />
                            <p class="card-text text-muted">{{ recipe.created_on}} <i class="far fa-heart"></i>
                                {{ recipe.number_of_likes }}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

</div>

{%endblock%}

templates/recipe.html
{% extends 'base.html' %} 
{% block content %}

<!-- Cocktail recipe detail -->
<div class="container">
    <div class="row">
        <div class="col card left top">
            <div class="card-body">
                <p class="card-text f-6" style="width: 40%;">{{ cocktail.serving | safe }} serving(s) | {{ cocktail.time | safe }}-mins
                </p>
                <p class="card-text" style="width: auto;"><span class="card-heading h2">Ingredients:</span>
                    <p class="card-text" style="width: 45%;">
                        {{ cocktail.ingredients | safe }}
                    </p>
                </p>
                <p class="card-text" style="width: auto;">     
                    <span class="card-heading h2">Directions:  </span>     
                    <p class="card-text" style="width: auto;">
                        {{ cocktail.directions | safe }}
                    </p>
                <div class="row">
                    
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-dark"><i class="far fa-comments"></i>
                            <!-- Total comments-->
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>

    <!-- Comments -->
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <!-- Comment body -->
                    {{ comment.body | linebreaks }}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                {% if commented %}
                <div class="alert alert-success alert-dismissible fade show" id="msg" role="alert">
                    Your comment is awaiting approval
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>   
                </div>
                
                {% else %}
                <!-- Comment form -->
                {% if user.is_authenticated %}
                <h4>Did you make this cocktail? Leave a comment:</h4>
                <p>Posting as: {{ user.username }}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-success btn-signup">Submit</button>
                </form>

                {% endif %}
                {% endif %} 
            </div>
        </div>
    </div>
</div>

{% endblock content %}